#!/bin/bash
trap 'exit' SIGINT SIGTERM
scp ~/tmp/query_annotate/flot.js akaariai@vipunen.hut.fi:public_html/djbench/query_annotate/
scp ~/tmp/query_annotate/index.html akaariai@vipunen.hut.fi:public_html/djbench/query_annotate/
scp ~/tmp/url_resolve/flot.js akaariai@vipunen.hut.fi:public_html/djbench/url_resolve/
scp ~/tmp/url_resolve/index.html akaariai@vipunen.hut.fi:public_html/djbench/url_resolve/
scp ~/tmp/url_resolve_flat/flot.js akaariai@vipunen.hut.fi:public_html/djbench/url_resolve_flat/
scp ~/tmp/url_resolve_flat/index.html akaariai@vipunen.hut.fi:public_html/djbench/url_resolve_flat/
scp ~/tmp/url_resolve_nested/flot.js akaariai@vipunen.hut.fi:public_html/djbench/url_resolve_nested/
scp ~/tmp/url_resolve_nested/index.html akaariai@vipunen.hut.fi:public_html/djbench/url_resolve_nested/
scp ~/tmp/url_reverse/flot.js akaariai@vipunen.hut.fi:public_html/djbench/url_reverse/
scp ~/tmp/url_reverse/index.html akaariai@vipunen.hut.fi:public_html/djbench/url_reverse/
scp ~/tmp/query_complex_filter/flot.js akaariai@vipunen.hut.fi:public_html/djbench/query_complex_filter/
scp ~/tmp/query_complex_filter/index.html akaariai@vipunen.hut.fi:public_html/djbench/query_complex_filter/
scp ~/tmp/qs_filter_chaining/flot.js akaariai@vipunen.hut.fi:public_html/djbench/qs_filter_chaining/
scp ~/tmp/qs_filter_chaining/index.html akaariai@vipunen.hut.fi:public_html/djbench/qs_filter_chaining/
scp ~/tmp/query_raw/flot.js akaariai@vipunen.hut.fi:public_html/djbench/query_raw/
scp ~/tmp/query_raw/index.html akaariai@vipunen.hut.fi:public_html/djbench/query_raw/
scp ~/tmp/query_all/flot.js akaariai@vipunen.hut.fi:public_html/djbench/query_all/
scp ~/tmp/query_all/index.html akaariai@vipunen.hut.fi:public_html/djbench/query_all/
scp ~/tmp/query_all_multifield/flot.js akaariai@vipunen.hut.fi:public_html/djbench/query_all_multifield/
scp ~/tmp/query_all_multifield/index.html akaariai@vipunen.hut.fi:public_html/djbench/query_all_multifield/
scp ~/tmp/model_save/flot.js akaariai@vipunen.hut.fi:public_html/djbench/model_save/
scp ~/tmp/model_save/index.html akaariai@vipunen.hut.fi:public_html/djbench/model_save/
scp ~/tmp/query_select_related/flot.js akaariai@vipunen.hut.fi:public_html/djbench/query_select_related/
scp ~/tmp/query_select_related/index.html akaariai@vipunen.hut.fi:public_html/djbench/query_select_related/
scp ~/tmp/query_delete/flot.js akaariai@vipunen.hut.fi:public_html/djbench/query_delete/
scp ~/tmp/query_delete/index.html akaariai@vipunen.hut.fi:public_html/djbench/query_delete/
scp ~/tmp/template_compilation/flot.js akaariai@vipunen.hut.fi:public_html/djbench/template_compilation/
scp ~/tmp/template_compilation/index.html akaariai@vipunen.hut.fi:public_html/djbench/template_compilation/
scp ~/tmp/template_render/flot.js akaariai@vipunen.hut.fi:public_html/djbench/template_render/
scp ~/tmp/template_render/index.html akaariai@vipunen.hut.fi:public_html/djbench/template_render/
scp ~/tmp/template_render_simple/flot.js akaariai@vipunen.hut.fi:public_html/djbench/template_render_simple/
scp ~/tmp/template_render_simple/index.html akaariai@vipunen.hut.fi:public_html/djbench/template_render_simple/
